apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-command-center
  namespace: devops-command-center

spec:
  replicas: 1

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: devops-command-center

  template:
    metadata:
      labels:
        app: devops-command-center

    spec:
      serviceAccountName: devops-command-center

      containers:
      - name: devops-command-center

        image: devops-command-center:v3

        imagePullPolicy: Never

        ports:
        - containerPort: 8000

        envFrom:
        - configMapRef:
            name: devops-command-center-config

        - secretRef:
            name: devops-command-center-secret

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        readinessProbe:
          httpGet:
            path: /health
            port: 8000

          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 8000

          initialDelaySeconds: 15
          periodSeconds: 20
