apiVersion: v1
kind: Secret

metadata:
  name: devops-command-center-secret
  namespace: devops-command-center

type: Opaque

stringData:
  DB_PASSWORD: "supersecret123"
  JWT_SECRET: "devops-command-center-jwt"
