apiVersion: v1
kind: Service

metadata:
  name: devops-command-center
  namespace: devops-command-center

spec:
  selector:
    app: devops-command-center

  ports:
  - port: 8000
    targetPort: 8000

  type: ClusterIP