apiVersion: v1
kind: Secret

metadata:
  name: {{ include "devops-command-center.fullname" . }}-secret

type: Opaque

stringData:
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
